# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4355df1d20b70174c8c80f891e7eb15c990e2f7d4f42d28b17adf1ba74ca6a2e5f0908994574d14079736413f48107659250f5bc06c84a38d4a16ccfd2155b1e

test:
  secret_key_base: 7706b99ebc8bd0343c480727b1e9ce47d9ec3bb08e7d76f0a8b6e069737c1fb8b5af164d2ec4bda4a4a66c431d49e28b6e4f96bd806f2afcf6626a1be281dd38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
